### ISSUE TITLE
Can't Build Nolo_OSVR_SteamVR Driver From Source

### ISSUE THREAD

**Issue by nanospork** [NOLOVR/NOLO-Others#6]
The source code available for the Nolo_OSVR_SteamVR driver is incomplete. It was apparently compiled using an old fork of the official SteamVR-OSVR plugin and an old version of OpenVR. At the very least, could you indicate which versions of SteamVR-OSVR and OpenVR were used? Or better, could a more complete source be uploaded?

**Comment by hradec** [comment]
Actually, there's NO SOURCE CODE AT ALL! 

Just already build windows shared libraries (DLL's)

Why create a git of it without source code? 

I was hopping to look at the source code to port it to Linux, but it seems NOLO company is not going to release the source code? 

seriously? 

You're basically using github as a free FTP service to provide download for your paying customers. 

is this allowed by github at all?

**Comment by hradec** [comment]
Closed without a word!! 

**"great customer support!"** 

HUAU!

**Comment by LyuzhouZ** [comment]
@hradec Please view source code here: https://github.com/OSVR/SteamVR-OSVR

**Comment by LyuzhouZ** [comment]
We used to provide the part of source code that we've modified. You can find them here: https://github.com/NOLOVR/NOLO-Others/tree/966958c1343019db616e2606168bf21b964ede82/NOLO_OSVR_SteamvrDriver/Source_Code
Note that you can't build solely on it because it's not complete. The rest of the (unmodified) source code are available on OSVR's Github page
